services:
  wb_api:
    image: prichetaboss/wp_api:test
    container_name: wb_api
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

    env_file:
      - .env

    ports:
      - "8000:8000"

    networks:
      - wb

networks:
  wb:
    driver: bridge
    external: true