services:
  wb_api:
    image: prichetaboss/wb_api:test
    container_name: wb_api
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

    env_file:
      - .env

    ports:
      - "8000:8000"

    networks:
      - wb

  worker:
    image: prichetaboss/wb_worker:test
    container_name: worker
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

    env_file:
      - .env

    ports:
      - "8001:8001"

    networks:
      - wb

networks:
  wb:
    driver: bridge
    external: true