services:
  db:
    image: postgres:16.11-alpine3.23
    container_name: db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db

    volumes:
      - ./data:/var/lib/postgresql/data

    networks:
      - pricheta_network

networks:
  pricheta_network:
    driver: bridge
    external: true