services:
  db:
    image: postgres:16.11-alpine3.23
    container_name: db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db

    volumes:
      - ./data:/var/lib/postgresql/data

    networks:
      - pricheta

networks:
  pricheta:
    driver: bridge
    external: true