services:
  debt_accounter:
    image: prichetaboss/debt_accounter:latest
    container_name: debt_accounter
    restart: unless-stopped
    env_file:
      - .env

    networks:
      - pricheta_network

networks:
  pricheta_network:
    driver: bridge
    external: true