services:
  tg_bot:
    image: prichetaboss/pricheta_bot:release-2026-02-24
    container_name: tg_bot
    restart: unless-stopped

    networks:
      - base

networks:
  base:
    name: base
    external: true