services:
  tg_bot:
    image: prichetaboss/pricheta_bot:latest
    container_name: tg_bot
    env_file:
      - .env
    restart: unless-stopped

    networks:
      - pricheta_network

networks:
  pricheta_network:
    driver: bridge
    external: true