services:
  pricheta_bot:
    image: prichetaboss/pricheta_bot:latest
    container_name: pricheta_bot
    restart: unless-stopped
    env_file:
      - .env

    networks:
      - pricheta_network

networks:
  pricheta_network:
    driver: bridge
    external: true