services:
  nginx:
    image: nginx:latest
    container_name: nginx
    env_file:
      - .env
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"


    networks:
      - pricheta_network

networks:
  pricheta_network:
    driver: bridge
    external: true