services:
  pricheta_bot:
    image: prichetaboss/pricheta_bot:latest
    container_name: pricheta_bot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

    env_file:
      - .env

    networks:
      - pricheta

networks:
  pricheta:
    driver: bridge
    external: true