services:
  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    restart: unless-stopped

    network_mode: host
    pid: host

    command:
      - '--path.rootfs=/host'

    volumes:
      - '/:/host:ro,rslave'

    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
