services:
  wb_db:
    image: postgres:16.11-alpine3.23
    container_name: wb_db
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wb_db

    volumes:
      - ./data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - wb

networks:
  wb:
    driver: bridge
    external: true